---
repos:
  - repo: local
    hooks:
      - id: xenon/app
        name: 'Xenon Code Complexity Checking (app)'
        language: docker_image
        entry: {{ cookiecutter.project_slug }} xenon -bB -mA -aA {{ cookiecutter.project_slug }}
        types: [python]
        pass_filenames: false

      - id: xenon/tests
        name: 'Xenon Code Complexity Checking (tests)'
        language: docker_image
        entry: {{ cookiecutter.project_slug }} xenon -bB -mA -aA tests
        types: [python]
        pass_filenames: false

      - id: flake8
        name: 'Flake8 Style Guide Checking'
        language: docker_image
        entry: {{ cookiecutter.project_slug }} flake8
        types: [python]

      - id: black
        name: 'Black Code Formatting'
        language: docker_image
        entry: {{ cookiecutter.project_slug }} black --check --diff
        types: [python]
        require_serial: true

      - id: yamllint
        name: 'YAML Linting'
        language: docker_image
        entry: {{ cookiecutter.project_slug }} yamllint
        types: [yaml]
